import { useEffect, useState, type FormEvent, type ReactNode } from 'react'
import { Link, useNavigate, useParams } from 'react-router-dom'
import { ArrowRight, Check, CreditCard, Info, LockKeyhole, ShieldCheck } from 'lucide-react'
import { Button } from '../components/Button'
import { membershipApi, type MembershipPlan } from '../lib/membershipApi'

const money = (value: number) => `${value.toLocaleString('sv-SE')} kr`
const formatDate = (value: string | null) => value ? new Intl.DateTimeFormat('sv-SE', { dateStyle: 'long' }).format(new Date(value)) : 'nästa period'

function Field({ label, children, hint }: { label: string; children: ReactNode; hint?: string }) {
    return <label className="grid gap-2 text-sm font-semibold text-primary"><span>{label}</span>{children}{hint && <span className="text-xs font-normal text-muted-foreground">{hint}</span>}</label>
}

export default function Checkout() {
    const { plan: planParam } = useParams(); const navigate = useNavigate(); const planNumber = Number(planParam)
    const [plan, setPlan] = useState<MembershipPlan | null>(null); const [current, setCurrent] = useState<MembershipPlan | null>(null); const [nextPeriod, setNextPeriod] = useState<string | null>(null)
    const [cardholder, setCardholder] = useState(''); const [card, setCard] = useState({ number: '', expiry: '', cvc: '' }); const [useAccountAddress, setUseAccountAddress] = useState(true)
    const [loading, setLoading] = useState(true); const [processing, setProcessing] = useState(false); const [loadError, setLoadError] = useState(''); const [formError, setFormError] = useState('')
    useEffect(() => { void membershipApi.checkout(planNumber).then((data) => { setPlan(data.plan); setCurrent(data.billing.plan); setNextPeriod(data.billing.nextAllocationDate) }).catch((requestError: Error) => setLoadError(requestError.message)).finally(() => setLoading(false)) }, [planNumber])
    if (loading) return <main className="mx-auto w-[calc(100%-2rem)] max-w-7xl flex-1 py-16"><p role="status" className="text-muted-foreground">Laddar betalning…</p></main>
    if (loadError || !plan) return <main className="mx-auto w-[calc(100%-2rem)] max-w-4xl flex-1 py-16"><h1>Checkout kunde inte laddas</h1><p className="mt-3 text-danger">{loadError || 'Medlemskapet hittades inte.'}</p><Link className="mt-6 inline-block text-link underline" to="/">Till startsidan</Link></main>
    const isUpgrade = Boolean(current && current.level < plan.level)
    const benefits = [`${plan.monthlyPoints} gåvopoäng vid start`, plan.level === 1 ? 'Tillgång till Simple-gåvor' : plan.level === 2 ? 'Tillgång till Simple- och Plus-gåvor' : 'Tillgång till hela gåvokatalogen', plan.maxSavedContacts === null ? 'Obegränsat med sparade kontakter' : `${plan.maxSavedContacts} sparade kontakter`, 'Oanvända poäng sparas på kontot']
    const submit = async (event: FormEvent) => { event.preventDefault(); setFormError(''); const digits = card.number.replace(/\s/g, ''); if (!cardholder.trim() || !/^\d{12,19}$/.test(digits) || !/^\d{2}\/\d{2}$/.test(card.expiry) || !/^\d{3,4}$/.test(card.cvc)) { setFormError('Fyll i alla kortuppgifter för att fortsätta.'); return } setProcessing(true); try { const result = await membershipApi.complete(planNumber, digits.slice(-4)); if (!result.success) { setFormError('Den simulerade betalningen nekades. Kontrollera uppgifterna och försök igen.'); return } if (!result.paymentId) { setFormError('Betalningen saknar kvittoreferens.'); return } navigate(`/checkout/success/${String(result.paymentId)}`, { replace: true }) } catch (requestError) { setFormError(requestError instanceof Error ? requestError.message : 'Betalningen kunde inte slutföras.') } finally { setProcessing(false) } }
    return <main className="flex-1 bg-background"><div className="mx-auto w-[calc(100%-2rem)] max-w-7xl pb-16 pt-10 sm:w-[calc(100%-4rem)] sm:pb-24 sm:pt-16">
        <div className="mx-auto max-w-3xl text-center"><span className="inline-flex items-center rounded-full bg-secondary px-4 py-2 text-xs font-semibold tracking-wide text-primary">Steg 2 av 2&nbsp; · &nbsp;Betalning & aktivering</span><h1 className="mt-7 text-4xl sm:text-5xl">{isUpgrade ? 'Uppgradera ditt medlemskap' : 'Slutför medlemskap'}</h1><p className="mx-auto mt-4 max-w-2xl text-base text-muted-foreground sm:text-lg">Aktivera ditt medlemskap och få dina första {plan.monthlyPoints} gåvopoäng direkt till ditt konto.</p></div>
        <div className="mt-8 flex items-start gap-3 rounded-card border border-accent/30 bg-accent-muted px-5 py-4 text-sm text-foreground sm:mt-10 sm:px-6"><Info className="mt-0.5 size-5 shrink-0 text-accent" aria-hidden="true" /><p><strong>Det här är en demo.</strong> Inga riktiga pengar dras och kortuppgifterna sparas aldrig eller skickas till vår backend.</p></div>
        <div className="mt-8 grid items-start gap-6 lg:grid-cols-[minmax(0,1.45fr)_minmax(20rem,0.85fr)] lg:gap-8">
            <form onSubmit={submit} className="rounded-card border border-border bg-surface p-6 sm:p-9"><div className="flex flex-wrap items-start justify-between gap-5 border-b border-border pb-7"><div className="flex gap-4"><span className="flex size-12 shrink-0 items-center justify-center rounded-control bg-secondary text-primary"><CreditCard className="size-6" aria-hidden="true" /></span><div><h2 className="text-2xl">Kortbetalning</h2><p className="mt-1 text-sm text-muted-foreground">Säker simulerad betalning för skolprojektet</p></div></div><div className="flex gap-1.5 text-[10px] font-bold text-muted-foreground"><span className="rounded border border-border px-2 py-1">VISA</span><span className="rounded border border-border px-2 py-1">MC</span><span className="rounded border border-border px-2 py-1">AMEX</span></div></div>
                <div className="mt-7 grid gap-5"><Field label="Kortinnehavarens namn"><input required autoComplete="cc-name" value={cardholder} onChange={(event) => setCardholder(event.target.value)} className="h-12 rounded-control border border-border bg-background px-4 text-sm font-normal text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" placeholder="För- och efternamn" /></Field><Field label="Kortnummer" hint="Använd valfria testuppgifter. Kortet debiteras aldrig."><input required autoComplete="cc-number" inputMode="numeric" value={card.number} onChange={(event) => setCard({ ...card, number: event.target.value })} className="h-12 rounded-control border border-border bg-background px-4 text-sm font-normal tracking-wide text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" placeholder="4242 4242 4242 4242" /></Field><div className="grid gap-5 sm:grid-cols-2"><Field label="Giltighet"><input required autoComplete="cc-exp" inputMode="numeric" value={card.expiry} onChange={(event) => setCard({ ...card, expiry: event.target.value })} className="h-12 rounded-control border border-border bg-background px-4 text-sm font-normal text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" placeholder="MM/ÅÅ" /></Field><Field label="CVC"><input required autoComplete="cc-csc" inputMode="numeric" value={card.cvc} onChange={(event) => setCard({ ...card, cvc: event.target.value })} className="h-12 rounded-control border border-border bg-background px-4 text-sm font-normal text-foreground outline-none transition focus:border-primary focus:ring-2 focus:ring-primary/15" placeholder="123" /></Field></div><label className="flex items-center gap-3 text-sm text-foreground"><input type="checkbox" checked={useAccountAddress} onChange={(event) => setUseAccountAddress(event.target.checked)} className="size-4 accent-primary" /> Använd adressen från mitt Presently-konto</label></div>
                <div className="mt-7 flex gap-3 rounded-control bg-secondary/60 p-4 text-sm text-primary"><ShieldCheck className="mt-0.5 size-5 shrink-0" aria-hidden="true" /><p><strong>Flexibelt medlemskap.</strong> Du kan avsluta när som helst från Mitt Presently. Dina poäng sparas på kontot.</p></div>{formError && <p className="mt-5 rounded-control border border-danger/30 bg-danger/5 px-4 py-3 text-sm text-danger" role="alert">{formError}</p>}<Button className="mt-7 h-12 w-full text-sm" disabled={processing} type="submit" icon={processing ? <LockKeyhole className="size-4 animate-pulse" /> : <ArrowRight className="size-4" />} iconPosition="right">{processing ? 'Behandlar betalningen…' : `Starta Presently ${plan.name}`}</Button><p className="mt-4 text-center text-xs text-muted-foreground">Genom att fortsätta godkänner du Presentlys villkor och integritetspolicy.</p>
            </form>
            <aside className="rounded-card border border-border bg-surface p-6 sm:p-8"><div className="flex items-center justify-between gap-4"><span className="text-[11px] font-bold tracking-[0.14em] text-accent">VALD MEDLEMSNIVÅ</span><Link className="text-sm font-semibold text-link underline" to="/#medlemskap">Byt nivå</Link></div><h2 className="mt-5 text-3xl">Presently {plan.name}</h2><p className="mt-2 text-sm text-muted-foreground">Gör det enkelt att visa omtanke, lite oftare.</p><div className="mt-7 grid grid-cols-2 gap-3 rounded-control bg-secondary/60 p-4"><div><p className="text-[10px] font-bold tracking-[0.12em] text-muted-foreground">GÅVOPOÄNG</p><p className="mt-1 text-xl font-bold text-primary">{plan.monthlyPoints} <span className="text-sm font-normal">p/mån</span></p></div><div><p className="text-[10px] font-bold tracking-[0.12em] text-muted-foreground">MÅNADSPRIS</p><p className="mt-1 text-xl font-bold text-primary">{money(plan.monthlyPrice)}</p></div></div><ul className="mt-7 space-y-4 border-b border-border pb-7">{benefits.map((benefit) => <li className="flex gap-3 text-sm" key={benefit}><Check className="mt-0.5 size-4 shrink-0 text-success" aria-hidden="true" />{benefit}</li>)}</ul><div className="mt-6 space-y-3 text-sm"><div className="flex justify-between text-muted-foreground"><span>Medlemskap</span><span>{money(plan.monthlyPrice)}</span></div><div className="flex justify-between text-muted-foreground"><span>Att betala idag</span><span className="font-bold text-primary">{money(plan.monthlyPrice)}</span></div><p className="pt-2 text-xs text-muted-foreground">Nästa poängperiod börjar {formatDate(nextPeriod)}.</p></div></aside>
        </div>
    </div></main>
}
